repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
      - id: ruff
        # Automatically fix issues and fail if fixes are applied.
        args: [--fix, --exit-non-zero-on-fix]
