name: vbase
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip

  # Required dependencies
  - hexbytes
  - numpy
  - pandas
  - python-dotenv
  - requests

  # Optional dependencies
  - setuptools

  # Test dependencies
  - pymongo

  - pip:
    # Required dependencies
    - pprint
    - web3>=6.0.0
