name: vbase
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip

  # Required dependencies
  - numpy
  - pandas
  - python-dotenv

  # Optional dependencies
  - setuptools

  # Test dependencies
  - pymongo

  - pip:
    # Required dependencies
    - beeprint
    - javascript
    - web3>=6.0.0
