[tool.isort]
# Avoid conflicts with black formatter.
profile = "black"
# Skip the main __init__.py that defines exports.
# This file is ordered logically rather than alphabetically.
skip = ["vbase/__init__.py"]

[tool.ruff]
# Enable flake8 and isort functionality.
lint.select = [
  "E",  # flake8 errors
  "F",  # flake8 pyflakes
  "I",  # isort
  "B",  # flake8 bugbear
  "C",  # flake8 complexity
  "W",  # flake8 warnings
  "A",  # flake8-builtins
  "D",  # pydocstyle
  "N",  # pep8-naming
  "Q",  # flake8-quotes
  "T",  # flake8-typing-imports
]

# Resolve conflicts by choosing one rule from each pair.
lint.extend-ignore = [
  "D203",  # Ignore D203 (use D211 instead)
  "D213",  # Ignore D213 (use D212 instead)
]

lint.ignore = [
  ### Intentionally disabled
  # Controversial: Loop control variable `record` not used within loop body.
  "B007",
  # Ignore "whitespace before ':'" (conflicts with black).
  "E203",

  ### TODO: Enable gradually
  # An abstract base class has no abstract methods or properties
  "B024",
  # Missing docstring in public method
  "D102",
  # Missing docstring in `__init__`
  "D107",
  # 1 blank line required between summary line and description
  "D205",
  # First line of docstring should be in imperative mood
  "D401",
  # Line too long
  "E501",
  # too-many-public-methods
  "PLR0904",
  # too-many-return-statements
  "PLR0911",
  # too-many-branches
  "PLR0912",
  # too-many-arguments
  "PLR0913",
  # too-many-locals
  "PLR0914",
  # too-many-statements
  "PLR0915",
]

# Set line length to match black's default.
line-length = 88

# Enable automatic fixes.
fix = true

# Configure isort settings.
[tool.ruff.lint.isort]
known-first-party = ["vbase"]  # Do not mess with vbase exports.
