name: Run Forwarder Tests Using a Public Dev Service

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run vbase-py forwarder tests using the public dev service
      env:
        VBASE_API_KEY: ${{ secrets.VBASE_API_KEY }}
      run: |
        chmod +x vbase/tests/scripts/run_tests_forwarder_pub_dev.sh
        vbase/tests/scripts/run_tests_forwarder_pub_dev.sh
