name: Run Forwarder Tests Using a Public Dev Service

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # v5
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Install dependencies
        uses: validityBase/vbase-github-actions/.github/actions/setup-python-deps@v1
        with:
          requirements-files: |
            requirements.txt
          python-version: "3.11"
          require-hashes: "true"

      - name: Run vbase-py forwarder tests using the public dev service
        env:
          VBASE_API_KEY: ${{ secrets.VBASE_API_KEY }}
        run: |
          chmod +x vbase/tests/scripts/run_tests_forwarder_pub_dev.sh
          vbase/tests/scripts/run_tests_forwarder_pub_dev.sh
