name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Pull and Run the vBase Commitment Service Docker container
      run: |
        docker pull ghcr.io/validitybase/commitment-service-localhost:latest
        docker run -d -p 8545:8545 --name commitment-service ghcr.io/validitybase/commitment-service-localhost:latest
        sleep 10 # Wait for the Ethereum test node to start

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run vbase-py tests
      run: |
        chmod +x vbase/tests/scripts/run_tests_localhost.sh
        vbase/tests/scripts/run_tests_localhost.sh

    - name: Stop and remove the Docker container
      run: |
        docker stop commitment-service
        docker rm commitment-service
