name: Run Localhost Tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # v5
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Log in to GitHub Container Registry
        # v4
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull and Run the vBase Commitment Service Docker container
        run: |
          docker pull ghcr.io/validitybase/commitment-service-localhost:latest
          docker run -d -p 8545:8545 --name commitment-service ghcr.io/validitybase/commitment-service-localhost:latest
          sleep 10 # Wait for the Ethereum test node to start

      - name: Set up Python
        # v6
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.11"

      - name: Install dependencies
        uses: ./.github/actions/setup-python-deps
        with:
          install-docs-first: "false"

      - name: Run vbase-py tests
        run: |
          chmod +x vbase/tests/scripts/run_tests_localhost.sh
          vbase/tests/scripts/run_tests_localhost.sh

      - name: Stop and remove the Docker container
        if: always()
        run: |
          docker stop commitment-service || true
          docker rm commitment-service || true
